### ISSUE TITLE
/docker-entrypoint.sh: Permission denied

### ISSUE THREAD

**Issue by kubagp1** [FragSoc/scpsl-docker#1]
```
root@vps-6028ccf0:/opt/scp-docker# docker run -p 7777:7777/udp -v $PWD/scpsl_config:/config scpsl
/bin/sh: 1: /docker-entrypoint.sh: Permission denied
```

How do I run container with this image?

Edit: I guess that's beacuse I copied this file from Windows to Linux using WinSCP
Edit2: Changing permissions in WinSCP to 777 fixed it but I still think that it is problem

**Comment by Laura7089** [comment]
Are you still having this issue?

**Comment by kubagp1** [comment]
> Are you still having this issue?

No, as I wrote, I fixed it by changing permissions to 777

**Comment by Laura7089** [comment]
I haven't been able to reproduce this with the info at hand - closing
